import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from './page.module.css';
import { Button } from "@/components/Button/Button";
import { UserCart } from "@/components/UserCart/UserCart";
import { getAllUsers } from "@/actions";
import Link from "next/link";
import { Tree } from "@/components/Tree/Tree";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const users = await getAllUsers()
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={styles.wrapper}>
        <header className={styles.header}>
          <Link href='/user/new'>
            <Button title='Add user'/>
          </Link>
        </header>
          <Tree data={users}/>
          {children}
        </main>
      </body>
    </html>
  );
}
